[build]
  command = "pip install -r requirements.txt && python main.py"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.11.0"

[[redirects]]
  from = "/api/*"
  to = "https://pdf-table-processor.onrender.com/:splat"
  status = 200
  force = true
