[build]
  command = "npm install && npm run build"  # Frontend build komutu
  publish = "dist"  # Frontend build çıktısının yolu
  port = 10000
  targetPort = 10000
[build.environment]
  NODE_VERSION = "18.x"  # Node.js sürümü

[[redirects]]
  from = "/api/*"
  to = "https://pdf-table-processor.onrender.com/api/:splat"  # Backend API'nize proxy
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://pdftableprocessor.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
